# Generated by Django 3.1 on 2020-11-25 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentasporcobrar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estilo',
            field=models.ForeignKey(default=({'id_estilo': 1},), on_delete=django.db.models.deletion.CASCADE, to='cuentasporcobrar.estilo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=({'id_rol': 2},), on_delete=django.db.models.deletion.CASCADE, to='cuentasporcobrar.rol'),
        ),
    ]
