# Generated by Django 3.1 on 2020-11-26 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentasporcobrar', '0008_auto_20201126_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_adeuddado',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estilo',
            field=models.ForeignKey(default=({'id_estilo': 1},), on_delete=django.db.models.deletion.CASCADE, to='cuentasporcobrar.estilo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=({'id_rol': 2},), on_delete=django.db.models.deletion.CASCADE, to='cuentasporcobrar.rol'),
        ),
    ]
