# Generated by Django 3.1 on 2020-11-26 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentasporcobrar', '0009_auto_20201126_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='total_adeuddado',
            new_name='total_adeudado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='Proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cuentasporcobrar.proveedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estilo',
            field=models.ForeignKey(default=({'id_estilo': 1},), on_delete=django.db.models.deletion.CASCADE, to='cuentasporcobrar.estilo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=({'id_rol': 2},), on_delete=django.db.models.deletion.CASCADE, to='cuentasporcobrar.rol'),
        ),
    ]
